# Generated by Django 3.1.4 on 2020-12-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
