# Generated by Django 3.1.4 on 2020-12-08 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0008_likecommentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes1',
            field=models.ManyToManyField(related_name='liked_comments', through='manager.LikeCommentUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likecommentuser',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_comment_table', to='manager.comment'),
        ),
    ]
