# Generated by Django 3.1.4 on 2020-12-09 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20201208_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='likes1',
            new_name='likes2',
        ),
    ]
