# Generated by Django 3.1.4 on 2020-12-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_book_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
