# Generated by Django 3.1.4 on 2020-12-18 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0016_book_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugBook',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('id', models.PositiveIntegerField(default=0, unique=True)),
                ('title', models.CharField(help_text='ну это типо погоняло книги', max_length=50, verbose_name='название')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('text', models.TextField()),
                ('count_rated_users', models.PositiveIntegerField(default=0)),
                ('count_all_stars', models.PositiveIntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('authors', models.ManyToManyField(related_name='slug_books', to=settings.AUTH_USER_MODEL)),
                ('users_like', models.ManyToManyField(related_name='liked_slug_books', through='manager.LikeBookUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slug_comments', to='manager.slugbook'),
        ),
        migrations.AddField(
            model_name='likebookuser',
            name='slug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slug_liked_user_table', to='manager.slugbook'),
        ),
    ]
