# Generated by Django 3.1.4 on 2020-12-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_auto_20201218_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slugbook',
            name='id',
        ),
        migrations.AlterField(
            model_name='likebookuser',
            name='slug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_slug_books', to='manager.slugbook'),
        ),
    ]
