# Generated by Django 3.1.4 on 2020-12-21 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0018_auto_20201219_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
        migrations.AlterField(
            model_name='slugbook',
            name='authors',
            field=models.ManyToManyField(related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slugbook',
            name='users_like',
            field=models.ManyToManyField(related_name='liked_books', through='manager.LikeBookUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='likebookuser',
            unique_together={('user', 'slug')},
        ),
        migrations.RemoveField(
            model_name='likebookuser',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
